const fs = require('fs');
const path = require('path');

/**
 * PHP emits missing-extension warnings before the script starts, so
 * display_startup_errors cannot reliably hide them. Build a per-user ini
 * when the bundled runtime contains optional directives for DLLs that are
 * not shipped with it. The original php.ini remains untouched.
 */

function stripIniQuotes(value) {
  const trimmed = value.trim();
  if (
    trimmed.length >= 2
    && ((trimmed.startsWith('"') && trimmed.endsWith('"'))
      || (trimmed.startsWith("'") && trimmed.endsWith("'")))
  ) {
    return trimmed.slice(1, -1);
  }
  return trimmed;
}

function getExtensionDirectory(iniText, phpDirectory) {
  const match = iniText.match(/^\s*extension_dir\s*=\s*(?:"([^"]+)"|'([^']+)'|([^;\s]+))/im);
  const configured = stripIniQuotes(match ? (match[1] || match[2] || match[3]) : 'ext');

  if (path.isAbsolute(configured)) {
    return configured;
  }
  return path.resolve(phpDirectory, configured);
}

function getExtensionFileCandidates(rawValue, extensionDirectory) {
  const value = stripIniQuotes(rawValue).trim();
  if (!value || value.startsWith(';') || value.startsWith('#')) {
    return [];
  }

  const normalized = value.replace(/[/\\]+/g, path.sep);
  const explicitPath = path.isAbsolute(normalized) || normalized.includes(path.sep);
  const fileName = path.basename(normalized);
  const names = [fileName];

  if (!path.extname(fileName)) {
    names.push(`${fileName}.dll`);
    if (!fileName.toLowerCase().startsWith('php_')) {
      names.push(`php_${fileName}.dll`);
    }
  }

  if (explicitPath) {
    return names.map((name) => path.join(path.dirname(normalized), name));
  }
  return names.map((name) => path.join(extensionDirectory, name));
}

function sanitizePhpIni(iniText, phpDirectory) {
  const extensionDirectory = getExtensionDirectory(iniText, phpDirectory);
  const absoluteExtensionDirectory = extensionDirectory.replace(/\\/g, '/');
  let missingExtensions = 0;
  let hasExtensionDirectory = false;

  const sanitizedLines = iniText.split(/\r?\n/).map((line) => {
    if (/^\s*extension_dir\s*=/i.test(line) && !/^\s*[;#]/.test(line)) {
      hasExtensionDirectory = true;
      return `extension_dir="${absoluteExtensionDirectory}"`;
    }

    if (/^\s*[;#]/.test(line)) {
      return line;
    }

    const extensionMatch = line.match(/^([ \t]*)(extension|zend_extension)\s*=\s*([^;#]*?)([ \t]*[;#].*)?$/i);
    if (!extensionMatch) {
      return line;
    }

    const candidates = getExtensionFileCandidates(extensionMatch[3], extensionDirectory);
    if (candidates.some((candidate) => fs.existsSync(candidate))) {
      return line;
    }

    missingExtensions += 1;
    const comment = `; disabled by POS runtime: missing ${stripIniQuotes(extensionMatch[3])}`;
    return `${extensionMatch[1]}${comment}${extensionMatch[4] || ''}`;
  });

  if (!hasExtensionDirectory) {
    sanitizedLines.unshift(`extension_dir="${absoluteExtensionDirectory}"`);
  }

  return {
    content: sanitizedLines.join('\n'),
    missingExtensions,
  };
}

function resolveSystemTimeZone() {
  const configured = typeof process.env.APP_TIMEZONE === 'string'
    ? process.env.APP_TIMEZONE.trim()
    : '';
  if (configured) return configured;

  try {
    return Intl.DateTimeFormat().resolvedOptions().timeZone || 'Africa/Cairo';
  } catch {
    return 'Africa/Cairo';
  }
}

/**
 * Return PHP CLI arguments that avoid startup warnings from absent optional
 * DLLs while preserving all settings and extensions that are available.
 *
 * @param {string} phpPath Absolute path to php.exe.
 * @param {string} writableDirectory App-owned directory for generated config.
 * @returns {string[]}
 */
function getPhpRuntimeArgs(phpPath, writableDirectory) {
  const phpDirectory = path.dirname(phpPath);
  const sourceIniPath = path.join(phpDirectory, 'php.ini');
  const baseArgs = [
    '-d', 'display_startup_errors=0',
    '-d', `date.timezone=${resolveSystemTimeZone()}`,
  ];

  try {
    if (!fs.existsSync(sourceIniPath)) {
      return baseArgs;
    }

    const sourceIni = fs.readFileSync(sourceIniPath, 'utf8');
    const sanitized = sanitizePhpIni(sourceIni, phpDirectory);
    if (sanitized.missingExtensions === 0) {
      // Do not depend on PHP's current working directory when the app is
      // launched from an NSIS shortcut. Point the CLI at the runtime's own
      // configuration explicitly.
      return ['-c', sourceIniPath, ...baseArgs];
    }

    fs.mkdirSync(writableDirectory, { recursive: true });
    const content = [
      '; Generated by POS System. Missing optional PHP extensions are disabled below.',
      sanitized.content,
    ].join('\n');
    const generatedIniPath = path.join(writableDirectory, 'php-runtime.ini');
    fs.writeFileSync(generatedIniPath, content, { encoding: 'utf8', mode: 0o600 });

    return ['-c', generatedIniPath, ...baseArgs];
  } catch (error) {
    // A read-only data directory should not prevent the app from starting.
    // Packaged runtimes also ship a corrected php.ini; this is a last-resort
    // fallback for environments where a generated copy cannot be written.
    console.warn('[PHP] Could not prepare sanitized runtime configuration:', error.message);
    return baseArgs;
  }
}

module.exports = {
  getPhpRuntimeArgs,
  resolveSystemTimeZone,
  sanitizePhpIni,
};
